---
abstract: 'perform European VAT calculations'
author:
  - 'Tony Bowden <kasei@tmtm.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.30
  Test::More: 0.17
configure_requires:
  ExtUtils::MakeMaker: 0
  Module::Build: 0.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-Tax-VAT
requires:
  Test::More: 0.17
  perl: 5.008
resources:
  bugtracker: https://github.com/jonasbn/Business-Tax-VAT/issues
  homepage: https://metacpan.org/pod/Business::Tax::VAT
  repository: https://github.com/jonasbn/Business-Tax-VAT.git
version: 1.07
