---
abstract: 'perform European VAT calculations'
author:
  - 'Tony Bowden <kasei@tmtm.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-Tax-VAT
provides:
  Business::Tax::VAT:
    file: lib/Business/Tax/VAT.pm
    version: 1.05
  Business::Tax::VAT::Price:
    file: lib/Business/Tax/VAT.pm
    version: 1.05
requires:
  Test::More: 0.17
  perl: 5.008
resources:
  homepage: http://search.cpan.org/dist/Business-Tax-VAT/
  repository: git://github.com/gitpan/Business-Tax-VAT.git
version: 1.05
